### ISSUE TITLE
Build Nunjucks AST instead of passing to HTMLAsset

### ISSUE THREAD

**Issue by devmattrick** [devmattrick/parcel-plugin-nunjucks#1]
The current functionality is to simple compile the Nunjucks template and then pass it to the HTMLAsset where it is turned into an AST using JSDOM. It may be beneficial performance-wise to use Nunjucks to generate an AST and resolve dependencies from there.

Ideally, the Nunjucks compiler should be used so there are no compatibility issues.

**Comment by Seminioni** [comment]
When will you start implementing this issue?

**Comment by devmattrick** [comment]
@Seminioni I'm not too sure. I have a bit of work to do before this and I'm not too sure if Nunjucks builds a proper AST at all, so I don't know how long this will take.

**Comment by chocolateboy** [comment]
Dependencies can't be determined statically from the AST. Dependencies are expressions (i.e. nonterminals) in nunjucks e.g. the following is valid:

```
{% set filename = "header.html" %}
{% include filename %}
```

Dependencies can also be loaded conditionally e.g.:

```
{% if foo > bar %}
    {% include "footer.html" %}
{% endif %}
```

Even dependencies that are represented as string literals can't be resolved statically, in general, since the interpretation of the string depends on the loader (i.e. they're identifiers rather than locators) e.g. `foo.html` could resolve to `src/html/foo.html` in the filesystem loader or to `http://example.com/foo.html` in a web loader.

**Comment by devmattrick** [comment]
Thanks for the insight, @chocolateboy. Turns out Nunjucks is a much more complicated engine that I expected. I'm having trouble finding time to maintain this project, but anyone is welcome to submit PRs if they are able to fix any of these issues.
