### ISSUE TITLE
Trigger live reload when a template is updated

### ISSUE THREAD

**Issue by jono-hayward** [devmattrick/parcel-plugin-nunjucks#8]
My project uses template inheritance and a lot of included sub templates to manage the markup, with an entry point file (`index.njk`) that looks like this:

```nunjucks
{% extends './templates/partials/_wrapper.njk' %}

{% block content %}

  {% include './templates/masthead.njk' %}

  {% include './templates/news.njk' %}

  {% include './templates/intro.njk' %}

  [...]

{% endblock %}
```

All of this structure works fine, except my live Parcel development server only refreshes the markup when `index.njk` is updated, not any of the templates it imports.

Is there any way to get Parcel to recognise when a sub template has been updated and refresh the markup?

**Comment by devmattrick** [comment]
The only way I can come up with for this to work is to have Parcel handle the dependency resolution instead of Nunjucks, but this would require that this project parse Nunjucks templates manually. I've seen a few projects that claim to parse Nunjucks into an AST but I'd prefer to use the actual nunjucks package so its largely compatible with any updates that may happen.

I'll have to look into it a bit more, I'm not sure if Nunjucks exposes any of these APIs.

**Comment by gterras** [comment]
Hi, 

Any news on this issue ?

**Comment by chocolateboy** [comment]
WFM. If you think you've found a bug, please raise a new issue with a reproducible test case.

Note that due to a [bug in Parcel](https://github.com/parcel-bundler/parcel/issues/943), HMR doesn't currently work (the HMR code isn't sent to the client) unless the page includes JavaScript.
